# docker-compose.yml
version: "3"
services:
  # app:
  #   restart: on-failure
  #   build: ./backend/
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://user:pass@postgres:5432/db
  #     NODE_ENV: development
  #     PORT: 8000
  #   ports:
  #     - "8000:8000"
  #   command: npm run dev
  #   volumes:
  #     - ./backend:/app/backend
  #     - /backend/node_modules

  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: phildbarto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: totally_a_real_password

volumes:
  local_pgdata:
  pgadmin-data:
